### ISSUE TITLE
Implement monitoring with Prometheus and Grafana

### ISSUE THREAD

**Issue by indravscode** [indravscode/go-fiber-boilerplate#16]
Add Prometheus and Grafana to the docker-compose file for application monitoring. This will include setting up Prometheus for metrics collection and Grafana for visualizing the data. Ensure that the Prometheus configuration is aligned with the application's metrics, and provide relevant dashboards in Grafana for easier monitoring.

**Comment by eduardomrodrigues** [comment]
Hi, @indrayyana ! Can I get this one?

**Comment by indravscode** [comment]
@eduardomrodrigues Sure! Feel free to submit a PR.
